### ISSUE TITLE
Return Non-Null Values for `send` failures

### ISSUE THREAD

**Issue by ecaustin** [ku-fpg/remote-json#1]
Right now the `send` method transmits a `Null` value for its failure cases.
This makes it incredibly hard to debug things externally, e.g. in hermit-shell.

We should change these `Null` values to be error objects, as specified by the standard:
http://www.jsonrpc.org/specification#error_object

I'm happy to spearhead this effort, but it may take me a day or two to get up to speed on the remote-json code base.

**Comment by andygill** [comment]
If you do so, talk to Justin, who is looking after the remote-json repo.

**Comment by ecaustin** [comment]
Yes, my intention is to get @jtdawso involved once I figure out exactly why `Nulls` are being returned in the first place, as the existing `send` method looks fairly robust as is.

**Comment by ecaustin** [comment]
I'm closing this with a won't fix.  remote-json handles properly constructed objects correctly which is realy all it should need to do.
