### ISSUE TITLE
Match up Server Replies with outgoing Method Requests

### ISSUE THREAD

**Issue by jtdawso** [ku-fpg/remote-json#12]

**Comment by andygill** [comment]
I think we need some functions, all of which will live in the Types module.

```
type IDTag = Int -- move into Types
```

Turn the full reply into a finite map of results.

```
 parseReply :: Value -> m (Map IDTag Value)
```

Lookup a specific Int in a finite map, and turn it into a result.

```
parseMethodResult :: Method a -> IDTag -> Map IDTag Value -> m a
```

I'd also change `mkMethodCall` to encode how we encode IDs.

```
mkMethodCall :: Method a -> IDTag -> JSONCall
```
