### ISSUE TITLE
Applicative not bundling properly

### ISSUE THREAD

**Issue by andygill** [ku-fpg/remote-json#15]
This might be a remote-monad problem.

**Comment by andygill** [comment]
I'm not pretty sure this is the `result` combinator forcing a bind.

**Comment by jtdawso** [comment]
I believe you are correct, I took out `result` in the `temperature` definition for the Blog.hs and it seems to bundle just fine.

**Comment by andygill** [comment]
The result is using the remote monad to possibly fail on fromJSON. We want it to fail in the IO monad, not the remote monad. I'm pushing a fix.

**Comment by andygill** [comment]
Its a pervasive change, and I've pushed it. I'm fixing the sever-side things now, which can be cleaned up a bit.

**Comment by andygill** [comment]
fixed!
